#!/usr/bin/env perl

use Digest::CRC;
use IO::File;
use strict;
use warnings;

my $ctx = Digest::CRC->new(type => 'crc32');

foreach my $filePath (@ARGV) {
	my $fh = IO::File->new($filePath, 'r');
	if (defined ($fh)) {
		$ctx->addfile($fh);
		undef($fh); # automatically closes the file
	} else {
		printf(STDERR "Error opening %s: %s\n", $filePath, $!);
	}

	printf("%s: %s\n", $filePath, $ctx->digest);
}

exit(0);
