#!/bin/sh

branch=master
if [ "$#" -eq 1 ]; then
	branch="$1"
fi

for remote in $(git remote); do
	if [ "$remote" = "vendor" ]; then
		continue
	fi
	if [ "$remote" = "shared" ]; then
		continue
	fi
	git push $remote "$branch";
done

exit 0
