#!/bin/sh

all=0
while [ $# -gt 0 ]; do
	case "$1" in
		-a|--all) all=1; shift ;;
		--) shift; break ;;
		*) break ;;
	esac
done

for r in */.hg; do
	repo="$(dirname "$r")"
	echo "$(pwd)/$repo"
	if hg -R "$repo" log --debug -r "$1" 2>/dev/null; then
		if [ "$all" -eq 0 ]; then
			exit 0
		fi
	fi
done
exit 0
