#!/usr/bin/env bash

set -e

if termux-battery-low; then
	echo "Battery is too low to encode files"
	exit 1
fi

find . -type f -name "*.mkv" -exec bash -c 'FILE="$1"; ffmpeg -i "${FILE}" -vn -c:a libmp3lame -y "${FILE%.mkv}.mp3";' _ '{}' \;
exit 0
