#!/usr/bin/env bash

set -x
set -euo pipefail

if termux-battery-low; then
	echo "Battery is too low to encode files"
	exit 1
fi

for mkv in *.mkv; do
	baseName=$(basename "$mkv" .mkv)
	out="$baseName.mp4"
	ffmpeg -i "$mkv" -map 0 -c copy -c:a aac "$out"
	rm -f "$mkv"
done

exit 0
