#!/usr/bin/env bash

set -xeuo pipefail

if termux-battery-low; then
	echo "Battery is too low to encode files"
	exit 1
fi

for mp4 in *.mkv; do
	baseName=$(basename "$mp4" .mkv)
	out="$baseName-720.mkv"
	nice -n 15 ffmpeg -i "$mp4" -c:v libx264 -crf 20 -preset veryslow -c:a copy -vf scale=-1:720 "$out"
	rm -f "$mp4"
done

exit 0
