#!/usr/bin/env bash

set -x
#set -euo pipefail

if termux-battery-low; then
	echo "Battery is too low to encode files"
	exit 1
fi

for mov in *.mov; do
	baseName=$(basename "$mov" .mov)
	out="$baseName.mp4"
	#ffmpeg -i "$mov" -map 0 -c copy -c:a aac "$out"
	ffmpeg -i "$mov" -vcodec h264 -acodec mp2 "$out"
done

exit 0
