#!/usr/bin/env bash

set -xeuo pipefail

if termux-battery-low; then
	echo "Battery is too low to encode files"
	exit 1
fi

deleteList=()
for x in *.mp3; do
	NAME=$(basename "$x" .mp3)
	if contains "$NAME" "desilence"; then
		continue;
	fi

	output="$NAME-desilence.mp3"
	if [ -f "$output" ]; then
		rm -fv "$output"
	fi

	nice -n 15 ffmpeg -hide_banner -loglevel panic -i "$x" -af silenceremove=stop_periods=-1:stop_duration=1:stop_threshold=-50dB "$output" &
	deleteList+=("$x")
done

wait

for mp3 in "${deleteList[@]}"; do
	rm -fv "$mp3"
done

exit 0
