#!/usr/bin/env bash

# usage:
# perl-intermittent-test YourTestSuite testMethod

U=$(uuid)
umask 027

output="/tmp/$U"
while env TEST_VERBOSE=1 perl -Ilib t/$1.t $2 >"$output" 2>&1; do :; done
cat "$output"
