#!/usr/bin/env perl

package main;
use strict;
use warnings;

my $ipAddr = $ARGV[0];

my $mac=`arp -a | grep $ipAddr | cut -f 4 -d ' '`;
chomp($mac);

my @macParts = split(m/:/, $mac);
shift(@macParts) foreach 0..2;
$mac = uc(join('', @macParts));

print "$mac\n";
exit 0;
