#!/usr/bin/env bash

set -xeo pipefail

TMP_SP=$(df -P /tmp | awk '/[0-9]%/{print $(NF-2)}')
VAR_TMP_SP=$(df -P /var/tmp | awk '/[0-9]%/{print $(NF-2)}')

if [[ "$TMP_SP" -ge "$VAR_TMP_SP" ]]; then
	TARGET=/tmp/$USER/Trash
else
	TARGET=/var/tmp/$USER/Trash
fi

mkdir -p $TARGET

if [ -d "/Volumes/trash/$USER" ]; then
	TARGET="/Volumes/trash/$USER"
elif [ "$XDG_DATA_HOME" = "" ]; then
	if [ ! -d "$TARGET" ]; then
		TARGET="$HOME/.Trash"
		mkdir -p "$TARGET"
	fi
else
	TARGET="$XDG_DATA_HOME/Trash"
fi

rsync -rv --progress --bwlimit=45000 "$@" "$TARGET/"
rm -rfv "$@"
