#!/usr/bin/env bash
# twitch-rationalize-filenames.sh
#
# Walks /mnt/totem/media/audio/music/Twitch/<letter>/<artist>/ directories and,
# for every file whose name prefix (everything before " (live)") does not match
# the containing folder name, writes a mv command to propose-renames.sh.
#
# THIS SCRIPT IS DRY-RUN ONLY. It writes proposals but executes nothing itself.

set -euo pipefail

ROOT="/mnt/totem/media/audio/music/Twitch"
OUTPUT="propose-renames.sh"

# Counters for summary
total_files=0
needs_rename=0
skipped_no_pattern=0

# Write output script header
{
    echo "#!/usr/bin/env bash"
    echo "# propose-renames.sh — generated by twitch-rationalize-filenames.sh"
    echo "# Review carefully before executing."
    echo "set -euo pipefail"
    echo ""
} > "$OUTPUT"

for letter_dir in "$ROOT"/*/; do
    [[ -d "$letter_dir" ]] || continue
    letter=$(basename "$letter_dir")
    [[ "$letter" == "@eaDir" ]] && continue

    for artist_dir in "$letter_dir"*/; do
        [[ -d "$artist_dir" ]] || continue
        artist_folder=$(basename "$artist_dir")
        [[ "$artist_folder" == "@eaDir" ]] && continue

        while IFS= read -r -d '' filepath; do
            filename=$(basename "$filepath")

            # Skip @eaDir pseudo-entries (shouldn't be files, but be safe)
            [[ "$filename" == "@eaDir" ]] && continue

            # Only process files that contain " (live)" in the name
            if [[ "$filename" != *" (live)"* ]]; then
                (( skipped_no_pattern++ )) || true
                continue
            fi

            (( total_files++ )) || true

            # Extract the suffix: everything from " (live)" onward
            suffix="${filename#*" (live)"}"
            # Reconstruct what the filename should be
            expected_filename="${artist_folder} (live)${suffix}"

            if [[ "$filename" != "$expected_filename" ]]; then
                old_path="${artist_dir}${filename}"
                new_path="${artist_dir}${expected_filename}"
                echo "mv -- $(printf '%q' "$old_path") $(printf '%q' "$new_path")" >> "$OUTPUT"
                (( needs_rename++ )) || true
            fi

        done < <(find "$artist_dir" -maxdepth 1 -type f -print0)
    done
done

echo "" >> "$OUTPUT"
echo "# End of proposed renames" >> "$OUTPUT"

chmod +x "$OUTPUT"

echo "Summary:"
echo "  Total files with '(live)' pattern : $total_files"
echo "  Proposed renames written           : $needs_rename"
echo "  Files skipped (no '(live)')        : $skipped_no_pattern"
echo ""
echo "Proposals written to: $OUTPUT"
