#!/usr/bin/env perl

package main;
use strict;
use warnings;
use Getopt::Std;
use JSON qw(decode_json);
use LWP::UserAgent;
use MIME::Base64;
use POSIX qw(EXIT_FAILURE EXIT_SUCCESS);

sub main {
	my $ua = LWP::UserAgent->new;
	$ua->timeout(120);
	$ua->env_proxy;

	my %opts;
	if (!getopts('v:n:', \%opts)) {
		return EXIT_FAILURE;
	}

	my @params;
	map { push(@params, join('=', $_, $opts{$_})) } keys(%opts);
	my $uri = 'http://perlapi.daybologic.co.uk/v2/uuid/generate?' . join('&', @params);

	my $response = $ua->get($uri);
	if ($response->is_success) {
		my $decoded = decode_json(decode_base64($response->decoded_content));
		foreach my $result (@{ $decoded->{results} }) {
			printf("%s\n", $result->{value});
		}
	} else {
		printf(STDERR "%s\n", $response->status_line);
		return EXIT_FAILURE;
	}

	return EXIT_SUCCESS;
}

exit(main());
