#!/usr/bin/env bash

set -e

if termux-battery-low; then
	echo "Battery is too low to encode files"
	exit 1
fi

for x in *.webm; do
	NAME=$(basename "$x" .webm)
	ffmpeg -i "$x" -vn -y "$NAME.mp3";
done
