#!/usr/bin/env bash

set -e

if termux-battery-low; then
	echo "Battery is too low to encode files"
	exit 1
fi

for x in *.wmv; do
	NAME=$(basename "$x" .wmv)
	ffmpeg -i "$x" -vn -acodec libmp3lame "$NAME.mp3";
done
