#!/bin/sh

set -ex

umask 077
file="$1"

editorFlags=""
if [ -z "$EDITOR" ]; then
	EDITOR="vi"
fi

if [ "$EDITOR" = "vi" ] || [ $EDITOR = "vim" ]; then
	editorFlags="-R"
fi

tmpfile=`mktemp zread.XXXXXX`
zcat "$file" > "$tmpfile"
"$EDITOR" "$editorFlags" "$tmpfile"
rm -f "$tmpfile"

exit 0;
