#!/usr/bin/env bash

set -euo pipefail

umask 077
file="$1"

editorFlags=""
if [ -z "$EDITOR" ]; then
	EDITOR="vi"
fi

if [ "$EDITOR" = "vi" ] || [ $EDITOR = "vim" ]; then
	editorFlags="-R"
fi

tmpfile=$(mktemp zread.XXXXXX --tmpdir)

function cleanup()
{
	rm -f "$tmpfile"
}
trap cleanup EXIT

zcat "$file" > "$tmpfile"
"$EDITOR" "$editorFlags" "$tmpfile"

exit 0;
